# Generated by Django 3.0.2 on 2022-05-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(blank=True, max_length=264, null=True)),
                ('country', models.CharField(blank=True, max_length=264, null=True)),
                ('country_code', models.CharField(blank=True, max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='iplog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(blank=True, max_length=264, null=True)),
                ('region', models.CharField(blank=True, max_length=264, null=True)),
                ('region_code', models.CharField(blank=True, max_length=264, null=True)),
                ('city', models.CharField(blank=True, max_length=264, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countryIP', to='dashboard.country')),
            ],
        ),
    ]
