# Generated by Django 3.0.2 on 2022-05-08 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20220508_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplog',
            name='continent',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='iplog',
            name='country_code',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='iplog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iplog',
            name='country',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.DeleteModel(
            name='country',
        ),
    ]
